services:
  php81-apache:
    image: webdevops/php-apache-dev:8.1-alpine
    ports:
      - ${DOCKER_LARAVEL_PORT}:80
    volumes:
      - ./:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    user: "${DOCKER_HOST_UID}:82"
    networks:
      - project-network

networks:
  project-network: {}