<x-layout>
    <x-slot:content>
        <div class="container py-4">
            <form action="{{ route('property.update', ['id' => $property->id]) }}" method="post">
                @csrf
                @method('put')
                <div class="d-flex justify-content-between align-items-center">
                    <h1>Edit Property</h1>
                    <div>
                        <a href="{{ route('property.list') }}" class="btn btn-warning">Cancel</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
                <div class="form-content w-50 mx-auto my-4">
                    <div class="row images-list mb-4">
                        <small>Image upload function is still not available, will be generated automaticaly when creating a property</small>
                        @foreach ($property->images as $image)
                        <div class="col">
                            <img src="{{ $image->image_url }}" class="card-img-top">
                        </div>
                        @endforeach
                    </div>
                    <div class="row mb-3">
                        <label for="name" class="col-4 col-form-label">Name</label>
                        <div class="col-8">
                            <input type="text" class="form-control" id="name" name="name" value="{{ $property->name }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="slug" class="col-4 col-form-label">Slug</label>
                        <div class="col-8">
                            <input type="text" class="form-control" id="slug" name="slug" value="{{ $property->slug }}">
                            <small>leave this empty then slug will be autogenerated</small>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="address" class="col-4 col-form-label">Address</label>
                        <div class="col-8">
                            <input type="text" class="form-control" id="address" name="address" value="{{ $property->address }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="description" class="col-4 col-form-label">Description</label>
                        <div class="col-8">
                            <textarea class="form-control" id="description" name="description" rows="4">{!! $property->description !!}</textarea>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="type" class="col-4 col-form-label">Type</label>
                        <div class="col-8">
                            <select class="form-select" id="type" name="type" required>
                                @foreach (\App\Enums\PropertyType::cases() as $type)
                                    <option value="{{ $type->value }}" {{ $property->type == $type->value ? 'selected' : '' }}>{{ ucfirst($type->value) }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="status" class="col-4 col-form-label">Status</label>
                        <div class="col-8">
                            <select class="form-select" id="status" name="status" required>
                                @foreach (\App\Enums\PropertyStatus::cases() as $status)
                                    <option value="{{ $status->value }}" {{ $property->status == $status->value ? 'selected' : '' }}>{{ ucfirst($status->value) }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="price" class="col-4 col-form-label">Price</label>
                        <div class="col-8">
                            <input type="number" class="form-control" id="price" name="price" value="{{ $property->price }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="number_of_bedrooms" class="col-4 col-form-label">Number of Bedrooms</label>
                        <div class="col-8">
                            <input type="number" class="form-control" id="number_of_bedrooms" name="number_of_bedrooms" value="{{ $property->number_of_bedrooms }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="number_of_bathrooms" class="col-4 col-form-label">Number of Bathrooms</label>
                        <div class="col-8">
                            <input type="number" class="form-control" id="number_of_bathrooms" name="number_of_bathrooms" value="{{ $property->number_of_bathrooms }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="number_of_car_spaces" class="col-4 col-form-label">Number of Car Spaces</label>
                        <div class="col-8">
                            <input type="number" class="form-control" id="number_of_car_spaces" name="number_of_car_spaces" value="{{ $property->number_of_car_spaces }}">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </x-slot:content>
</x-layout>